"""
Django settings for Hellocial_0_1 project.

Generated by 'django-admin startproject' using Django 1.8.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# 导入日志配置
from logs.log_config import LOGGING




# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '0wvdb7=2p=s*vjpej6@6x7h@3cb184gu$rt83^$pr=vv-yk8ry'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

import logging

if DEBUG:
    logger = logging.getLogger('django.request')
else:
    logger = logging.getLogger('django.request')

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.products',
    'apps.users',
    'apps.scripts'
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',  # csrf中间件
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'Hello_Server.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Hello_Server.wsgi.application'

AUTH_USER_MODEL = 'users.User'  # 指定django认证系统使用的用户模型类

# 设置Django框架的缓存
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        # 设置django缓存的数据保存在redis数据库中
        "LOCATION": "redis://127.0.0.1:6379/5",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

# Django的session存储设置
SESSION_ENGINE = "django.contrib.sessions.backends.cache"

# 设置session信息存储在CACHES配置项default对应的redis中
SESSION_CACHE_ALIAS = "default"

# 配置login_required 在验证不通过时候跳转的路径
LOGIN_URL = '/redirct'

# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'hellocial',
        'HOST': '127.0.0.1',
        'PORT': 3306,
        'USER': 'root',
        'PASSWORD': 'mysql',
    }
}

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'zh-Hans'  # 设置中文

TIME_ZONE = 'Asia/Shanghai'  # 设置时区

USE_I18N = True

USE_L10N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

# STATIC_ROOT = os.path.join(BASE_DIR, 'static')

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static"),
)

# 验证码图片过期时间 5分钟
IMAGE_CODE_REDIS_EXPIRES = 300
# 验证码的字体文件路径
FONT_FILE_PATH = os.path.join(BASE_DIR, "static/actionj.ttf")
# token的有效期
TOKEN_REDIS_EXPIRES = 3600
# 默认的有效时长(单位:小时)
ACCOUNTS_VALID_HOURS = 3
# 分页每页数据条数
PER_PAGE_COUNTS = 20
# 广告主默认开户数
ACCOUNTS_CREATE_COUNT = 5
# 最小用户名长度
USERNAME_MIN_LENGTH = 4
# 用户超时时长
SESSION_EXPIRY_SECONDS = 1800

# 手机app端程序秘钥过期时间
PHONE_SECRET_KEY_EXPIRE = 3600 * 24

RUOKUAI_SOFT_ID = 1

RUOKUAI_SOFT_KEY = 'b40ffbee5c1cf4e38028c197eb2fc751'

RUOKUAI_CAPTCHA_TYPE = {
    0: 5000,
    1: 4000,
    2: 2000,
    3: 1000,
    4: 3000
}

# pdf文件的根目录
PDF_ROOT = os.path.join(BASE_DIR,'pdf_files')